name: 'check-if-skip'
description: ''

inputs:
  checksum-file:
    description: 'checksum-file'
    required: true

outputs:
  skip:
    description: "should skip?"
    value: ${{ steps.check-if-skip.outputs.skip }}

runs:
  using: "composite"
  steps:
    - id: check-if-skip
      run: |
        if sha256sum -c ${{ inputs.checksum-file }} --status; then
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
