name: haskell

on:
  push:
    tags:
      - "*"
    branches:
      - release

  pull_request:

env:
  IMAGE_NAME: hstreamdb/haskell

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-if-skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check-if-skip
        id: check-if-skip
        uses: ./.github/actions/check-if-skip
        with:
          checksum-file: checksum/haskell.sha256sum

  build:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.4:8.10:latest", "8.10.7", "9.0.1:9.0", "9.2.1:9.2"]
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build & push images
        run: |
          IFS=':' read -ra image_tags < <(echo "${{ matrix.ghc }}")
          ghc_version="${image_tags[0]}"
          image_tag="${ghc_version}"
          docker pull $IMAGE_NAME:${image_tag} || true
          DOCKER_BUILDKIT=1 docker build . -f Dockerfile --build-arg GHC=${ghc_version} --tag $IMAGE_NAME:${image_tag}

          if [ "${{ github.event_name }}" == 'push' ]; then
            docker push hstreamdb/haskell:${image_tag}
            for tag in "${image_tags[@]:1}"; do
              docker tag $IMAGE_NAME:$image_tag $IMAGE_NAME:$tag
              docker push $IMAGE_NAME:$tag
            done
          fi
