name: grpc

on:
  push:
    tags:
      - '*'
    branches:
      - release

  pull_request:

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-if-skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check-if-skip
        uses: ./.github/actions/check-if-skip
        with:
          checksum-file: checksum/grpc.sha256sum

  build:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push images
        run: |
          if [ "${{ github.event_name }}" == 'push' ]; then
            HS_DIR="." ./build.sh build_grpc
            HS_DIR="." ./build.sh push_grpc
            HS_DIR="." ./build.sh push_grpc_manifest
          else
            ./build.sh build_grpc
          fi
