name: hadmin-store

on:
  push:
    tags:
      - '*'
    branches:
      - release

  pull_request:

env:
  IMAGE: ghcr.io/hstreamdb/hadmin-store:latest

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-if-skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: check-if-skip
        run: |
          if sha256sum -c checksum/hadmin_store.sha256sum --status; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

  build:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push images
        run: |
          # XXX: The more PARALLEL you set, the more memory is required for building with arm64
          if [ "${{ github.event_name }}" == 'push' ]; then
            docker buildx build . --platform linux/amd64,linux/arm64 \
              --build-arg PARALLEL=1 \
              --push -f dockerfiles/hadmin_store -t $IMAGE
          else
            docker buildx build . --platform linux/amd64,linux/arm64 \
              --build-arg PARALLEL=1 \
              -f dockerfiles/hadmin_store -t $IMAGE
          fi
