name: hsthrift

on:
  push:
    tags:
      - "*"
    branches:
      - release

  # XXX:
  # pull_request:

env:
  IMAGE: ghcr.io/hstreamdb/hsthrift:latest

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-if-skip.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check-if-skip
        id: check-if-skip
        uses: ./.github/actions/check-if-skip
        with:
          checksum-file: checksum/hsthrift.sha256sum

  build:
    needs: init
    if: ${{ needs.init.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push images
        run: |
          HS_DIR='.' ./build.sh build_hsthrift
          HS_DIR='.' ./build.sh push_hsthrift
          HS_DIR='.' ./build.sh push_hsthrift_manifest
